mlflow:
  experiment_name: "walmart_sales_forecasting"
  tracking_uri: "file:./mlruns"

metric: rmse

models:
  random_forest:
    enabled: true
    params:
      random_state: 42
      n_jobs: -1
    tuning:
      enabled: true
      method: randomized
      n_iter: 10
      cv: 3
      scoring: neg_root_mean_squared_error
      param_distributions:
        n_estimators: [50, 100, 150]
        max_depth: [10, 20, 30, null]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
        max_features: ["sqrt", "log2", null]

  gradient_boosting:
    enabled: true
    params:
      random_state: 42
    tuning:
      enabled: true
      method: randomized
      n_iter: 10
      cv: 3
      scoring: neg_root_mean_squared_error
      param_distributions:
      n_estimators: [50, 100, 150]
      learning_rate: [0.01, 0.05, 0.1]
      max_depth: [2, 3, 4]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      max_features: ["sqrt", "log2", null]

  xgboost:
    enabled: true   
    params:
      random_state: 42
    tuning:
      enabled: true
      method: randomized
      n_iter: 10
      cv: 3
      scoring: neg_root_mean_squared_error
      param_distributions:
        n_estimators: [50, 100, 150]
        learning_rate: [0.01, 0.05, 0.1]
        max_depth: [4, 6, 8, 10]
        subsample: [0.7, 0.8, 0.9, 1.0]
        colsample_bytree: [0.7, 0.8, 0.9, 1.0]
